### ISSUE TITLE
请问 #customRequestHandler={随意的字符}  如何理解？

### ISSUE THREAD

**Issue by supermayx** [soulsands/trilium-ios-shortcut#1]
我是直接按原文拷贝么？还是说可以将{随意的字符}替换为自己想要的任意字符，比如写成这样：

#customRequestHandler=takenote

谢谢你！

**Comment by soulsands** [comment]
yes, `#customRequestHandler=takenote ` will work.  Sorry the document may not be very clear. It would be appreciated if you could help optimize it. :)

**Comment by supermayx** [comment]
Thanks, already got it working now, still trying to understand it and tweak it. 
If I find more questions, should I start new issue or stay in this issue?  Which way do you prefer?

**Comment by soulsands** [comment]
Glad it works.
> should I start new issue or stay in this issue? 
Both them would be fine.
