### ISSUE TITLE
can we set title to the first line of input text note?

### ISSUE THREAD

**Issue by supermayx** [soulsands/trilium-ios-shortcut#2]
by default, the title will be a fixed text, or "from ios shortcut".
can we extract the first line or first several words as the title of new note?

BTW, I just found a typo in line 15 of handler.js , LOL

>    
    let {content} = req.body;
    if (content) {
        let {title, labelString = ""} = req.body;
        if (!title) {
            title = "from ios shor tcut";
        }

**Comment by soulsands** [comment]
handler.js has been updated. It will use first 20 strings of the content if the title is empty.

**Comment by supermayx** [comment]
fantastic! Now I can send text or photo via shortcut. Thank you so much!

AND, can we send other file types? such as pdf, web archive (useful when i want to clip a web page using safari)

**Comment by soulsands** [comment]
> AND, can we send other file types? 

yes, you can copy the file first, and use the file shortcut to send.
